name: Release
on:
  push:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set version id
        run: echo "version=1.${{ github.run_number }}" >> gradle.properties
      - name: Debug settings.gradle
        run: cat settings.gradle
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jpackage
      - name: Debug jpackage output
        run: ls ./build/jpackage
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.${{ github.run_number }}.${{ matrix.os }}
          release_name: 1.${{ github.run_number }} ${{ matrix.os }}
          draft: false
          prerelease: false
      - name: Upload MacOS dmg
        if: ${{ matrix.os == 'macos' }}
        id: upload-macos-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/FoggyDicom-1.${{ github.run_number }}.dmg
          asset_name: FoggyDicom-1.${{ github.run_number }}.dmg
          asset_content_type: application/x-apple-diskimage
      - name: Upload MacOS pkg
        if: ${{ matrix.os == 'macos' }}
        id: upload-macos-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/FoggyDicom-1.${{ github.run_number }}.pkg
          asset_name: FoggyDicom-1.${{ github.run_number }}.pkg
          asset_content_type: application/x-apple-diskimage
      - name: Upload Windows Release Asset
        if: ${{ matrix.os == 'windows' }}
        id: upload-windows-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/FoggyDicom-1.${{ github.run_number }}.exe
          asset_name: FoggyDicom-1.${{ github.run_number }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
