name: Deployment
on:
  push:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jpackage
      - name: Rename .dmg file
        run: mv ./build/jpackage/FoggyDicom-1.0.dmg FoggyDicom.dmg
      - name: Wat
        run: ls ./build/jpackage
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload MacOS Release Asset
        if: ${{ matrix.os }} == "macos-latest"
        id: upload-macos-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/FoggyDicom.dmg
          asset_name: macos dmg
          asset_content_type: application/x-apple-diskimage
#      - name: Upload MacOS Release Asset
#        if: ${{ matrix.os == "windows-latest" }}
#        id: upload-macos-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./build/FoggyDicom.dmg
#          asset_name: macos dmg
#          asset_content_type: application/x-apple-diskimage
